name: 自动测速

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 下载 CloudFlare IP 列表
        run: |
          wget -qO- https://www.cloudflare-cn.com/ips-v4/ | tee ip.txt

      - name: 配置
        run: |
          set -e
          chmod +x CloudflareST
          pip install pandas

      - name: 测速
        run: |
          set -e
          ./CloudflareST -cfcolo HKG -sl 5 -n 800 -dn 5 -o HKG.csv
          ./CloudflareST -cfcolo KHH -sl 5 -n 800 -dn 5 -o KHH.csv
          ./CloudflareST -cfcolo SIN -sl 5 -n 800 -dn 5 -o SIN.csv
          ./CloudflareST -cfcolo NRT -sl 5 -n 800 -dn 5 -o NRT.csv
          ./CloudflareST -cfcolo SEA -sl 5 -n 800 -dn 5 -o SEA.csv
          ./CloudflareST -cfcolo LHR -sl 5 -n 800 -dn 5 -o LHR.csv
          ./CloudflareST -cfcolo TPE -sl 5 -n 800 -dn 5 -o TPE.csv
          ./CloudflareST -cfcolo FRA -sl 5 -n 800 -dn 5 -o FRA.csv
          ./CloudflareST -cfcolo OKA -sl 5 -n 800 -dn 5 -o OKA.csv
          ./CloudflareST -cfcolo ICN -sl 5 -n 800 -dn 5 -o ICN.csv
          ./CloudflareST -cfcolo WAW -sl 5 -n 800 -dn 5 -o WAW.csv
          rm -f ip.txt
          python csv_to_txt.py

      - name: 提交并推送更改
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.txt
          git commit -m "自动优选"
          git push
